name: Continuous Integration

on: 
    push: 
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
    
      - name: Restore dependencies
        run: dotnet restore HelloWorld/HelloWorld.csproj

      - name: Build application
        run: dotnet build HelloWorld/HelloWorld.csproj --no-restore

      - name: Publish application
        run: dotnet publish HelloWorld/HelloWorld.csproj --output ./publish

      - name: Create ZIP package
        run: zip -r HelloWorld.zip ./publish

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v7
        with:
          name: HelloWorld
          path: HelloWorld.zip
    
      - name: Build Docker image
        run: docker build -t helloworld:latest ./HelloWorld
      
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name helloworld helloworld:latest

      - name: Test Docker container
        run: curl http://localhost:8080